//
//  ProductTableRouter.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductTableRoutingLogic {
  func routeToProductDetailsVC(segue: UIStoryboardSegue?)
}

protocol ProductTableDataPassing {
    var dataStore: ProductTableDataStore? { get }
}

class ProductTableRouter: NSObject, ProductTableRoutingLogic, ProductTableDataPassing {
    var dataStore: ProductTableDataStore?
    weak var viewController: ProductTableVC?
  
  // MARK: Routing
    
    func routeToProductDetailsVC(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ProductDetailsVC
            var destinationDS = destinationVC.router?.dataStore
            passDataToDetailVC(destination: &destinationDS!)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductDetailsVC") as! ProductDetailsVC
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDetailVC(destination: &destinationDS)
            navigateToDetailVC(source: viewController!, destination: destinationVC)
        }
    }
    
// MARK: Navigation
    
    func navigateToDetailVC(source: ProductTableVC, destination: ProductDetailsVC) {
      source.show(destination, sender: nil)
    }

// MARK: Passing data
    
    fileprivate func passDataToDetailVC(destination: inout ProductDetailsDataStore) {
        destination.product = dataStore?.selectedProduct
    }
}
