//
//  ProductTableModels.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductTable {
  // MARK: Use cases
    enum LoadData {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum FilterCategory {
        struct Request {
            var filterText:String?
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
