//
//  ProductTableWorker.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductTableWorker {
    
    func loadData(success: @escaping (_ result: Bool) -> Void) {
        let mapper = ProductMapper()
        APILoader.parseProductData(mapper: mapper, success: success)
    }
    
    func populateData() -> [Goods] {
        var goods = [Goods]()
        let products = Product.mr_findAll() as? [Product]
        for product in products! {
            var categoryArray = Array<String>()
            for item in product.categories! {
                let category = item as! Category
                if let title = category.title {
                    categoryArray.append(title)
                }
            }
            let item = Goods(product: product, categories: categoryArray)
            goods.append(item)
        }
        return goods
    }
}
