//
//  ProductDetailsModels.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetails {
  // MARK: Use cases
    enum ShowDesctiptions {
        struct Request {
        }
        
        struct Response {
            var product: Goods
            var categories: String
        }
        
        struct ViewModel {
            var product: Goods
            var categories: String
        }
    }
}
