//
//  ProductDetailsRouter.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDetailsRoutingLogic {
}

protocol ProductDetailsDataPassing {
  var dataStore: ProductDetailsDataStore? { get }
}

class ProductDetailsRouter: NSObject, ProductDetailsRoutingLogic, ProductDetailsDataPassing {
    weak var viewController: ProductDetailsVC?
    var dataStore: ProductDetailsDataStore?
  
  // MARK: Routing
  
}
