//
//  ProductDetailsPresenter.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 20.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresentationLogic {
    func showDescriptions(response: ProductDetails.ShowDesctiptions.Response)
}

class ProductDetailsPresenter: ProductDetailsPresentationLogic {
  weak var viewController: ProductDetailsDisplayLogic?
  
  // MARK: Do something
    func showDescriptions(response: ProductDetails.ShowDesctiptions.Response) {
        let viewModel = ProductDetails.ShowDesctiptions.ViewModel(product: response.product, categories: response.categories)
        viewController?.showDescriptions(viewModel: viewModel)
    }
}
