//
//  ProductTablePresenterTests.swift
//  GoustoTest
//
//  Created by Oleksiy Chebotarov on 22.01.2018.
//  Copyright (c) 2018 OleksiyCheborarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GoustoTest
import XCTest

class ProductTablePresenterTests: XCTestCase {
  // MARK: Subject under test

  var sut: ProductTablePresenter!

  // MARK: Test lifecycle

  override func setUp() {
    super.setUp()
    setupProductTablePresenter()
  }

  override func tearDown() {
    super.tearDown()
  }

  // MARK: Test setup

  func setupProductTablePresenter() {
    sut = ProductTablePresenter()
  }

  // MARK: Test doubles

    class ProductTableDisplayLogicSpy: ProductTableDisplayLogic {
        var displayLoadingData = false
        
        func displayLoadingData(viewModel: ProductTable.LoadData.ViewModel) {
            displayLoadingData = true
        }
        var reloadTableView = false
        func reloadTableView(viewModel: ProductTable.FilterCategory.ViewModel) {
            reloadTableView = true
        }
        
  }

  // MARK: Tests

    func testLoadingComplete() {
    // Given
    let spy = ProductTableDisplayLogicSpy()
    sut.viewController = spy
    let responce = ProductTable.LoadData.Response()

    // When
    sut.loadingComplete(response: responce)

    // Then
    XCTAssertTrue(spy.displayLoadingData, "loadingComplete(response:) should ask the view controller to display the result")
    }
    
    func testReloadTableView() {
        // Given
        let spy = ProductTableDisplayLogicSpy()
        sut.viewController = spy
        let responce = ProductTable.FilterCategory.Response()
        
        // When
        sut.filterCategory(response: responce)
        
        // Then
        XCTAssertTrue(spy.reloadTableView, "filterCategory(response:) should ask the view controller to display the result")
    }
}

